export const DummyFilterItems = [
  {
    id: 1,
    Brand: "Whiskas",
    ProductType: "Dog Food",
    Price: "From $179",
    BreedType: "All breeds",
    VegNonveg: "Veg",
    src: "/assets/FilterItem/Whiskas.png",
  },
  {
    id: 2,
    Brand: "Himalaya",
    ProductType: "Dog Food",
    Price: "From $179",
    BreedType: "Adult Breed",
    VegNonveg: "Non-veg",
    src: "/assets/FilterItem/Himalaya.png",
  },
  {
    id: 3,
    Brand: "Acana",
    ProductType: "Dog Food",
    Price: "From $179",
    BreedType: "Adult Breed",
    VegNonveg: "Veg",
    src: "/assets/FilterItem/Acana.png",
  },
  {
    id: 4,
    Brand: "Whiskas",
    ProductType: "Dog Food",
    Price: "From $179",
    BreedType: "All breeds",
    VegNonveg: "Veg",
    src: "/assets/FilterItem/Whiskas.png",
  },
  {
    id: 5,
    Brand: "Royal Canin",
    ProductType: "Dog Food",
    Price: "From $179",
    BreedType: "Adult Breed",
    VegNonveg: "Non-veg",
    src: "/assets/FilterItem/RoyalCanin.png",
  },
  {
    id: 6,
    Brand: "Himalaya",
    ProductType: "Dog Food",
    Price: "From $179",
    BreedType: "Adult Breed",
    VegNonveg: "Non-veg",
    src: "/assets/FilterItem/Himalaya.png",
  },
  {
    id: 7,
    Brand: "Whiskas",
    ProductType: "Dog Food",
    Price: "From $179",
    BreedType: "All breeds",
    VegNonveg: "Veg",
    src: "/assets/FilterItem/Whiskas.png",
  },
  {
    id: 8,
    Brand: "Acana",
    ProductType: "Dog Food",
    Price: "From $179",
    BreedType: "Adult Breed",
    VegNonveg: "Veg",
    src: "/assets/FilterItem/Acana.png",
  },
  {
    id: 9,
    Brand: "Whiskas",
    ProductType: "Dog Food",
    Price: "From $179",
    BreedType: "All breeds",
    VegNonveg: "Veg",
    src: "/assets/FilterItem/Whiskas.png",
  },
  {
    id: 10,
    Brand: "Acana",
    ProductType: "Dog Food",
    Price: "From $179",
    BreedType: "Adult Breed",
    VegNonveg: "Veg",
    src: "/assets/FilterItem/Acana.png",
  },
  {
    id: 11,
    Brand: "Himalaya",
    ProductType: "Dog Food",
    Price: "From $179",
    BreedType: "Adult Breed",
    VegNonveg: "Non-veg",
    src: "/assets/FilterItem/Himalaya.png",
  },
  {
    id: 12,
    Brand: "Royal Canin",
    ProductType: "Dog Food",
    Price: "From $179",
    BreedType: "Adult Breed",
    VegNonveg: "Non-veg",
    src: "/assets/FilterItem/RoyalCanin.png",
  },
//   {
//     id: 3,
//     Brand: "Whiskas",
//     ProductType: "Dog Food",
//     BreedType: "All breeds",
//     VegNonveg: "Veg",
//     src: "/assets/FilterItem/Whiskas.png",
//   },
//   {
//     id: 3,
//     Brand: "Whiskas",
//     ProductType: "Dog Food",
//     BreedType: "All breeds",
//     VegNonveg: "Veg",
//     src: "/assets/FilterItem/Whiskas.png",
//   },
//   {
//     id: 3,
//     Brand: "Whiskas",
//     ProductType: "Dog Food",
//     BreedType: "All breeds",
//     VegNonveg: "Veg",
//     src: "/assets/FilterItem/Whiskas.png",
//   },
//   {
//     id: 3,
//     Brand: "Whiskas",
//     ProductType: "Dog Food",
//     BreedType: "All breeds",
//     VegNonveg: "Veg",
//     src: "/assets/FilterItem/Whiskas.png",
//   },
//   {
//     id: 3,
//     Brand: "Whiskas",
//     ProductType: "Dog Food",
//     BreedType: "All breeds",
//     VegNonveg: "Veg",
//     src: "/assets/FilterItem/Whiskas.png",
//   },
//   {
//     id: 3,
//     Brand: "Whiskas",
//     ProductType: "Dog Food",
//     BreedType: "All breeds",
//     VegNonveg: "Veg",
//     src: "/assets/FilterItem/Whiskas.png",
//   },
//   {
//     id: 3,
//     Brand: "Whiskas",
//     ProductType: "Dog Food",
//     BreedType: "All breeds",
//     VegNonveg: "Veg",
//     src: "/assets/FilterItem/Whiskas.png",
//   },
//   {
//     id: 3,
//     Brand: "Whiskas",
//     ProductType: "Dog Food",
//     BreedType: "All breeds",
//     VegNonveg: "Veg",
//     src: "/assets/FilterItem/Whiskas.png",
//   },
//   {
//     id: 3,
//     Brand: "Whiskas",
//     ProductType: "Dog Food",
//     BreedType: "All breeds",
//     VegNonveg: "Veg",
//     src: "/assets/FilterItem/Whiskas.png",
//   },
//   {
//     id: 3,
//     Brand: "Whiskas",
//     ProductType: "Dog Food",
//     BreedType: "All breeds",
//     VegNonveg: "Veg",
//     src: "/assets/FilterItem/Whiskas.png",
//   },
//   {
//     id: 3,
//     Brand: "Whiskas",
//     ProductType: "Dog Food",
//     BreedType: "All breeds",
//     VegNonveg: "Veg",
//     src: "/assets/FilterItem/Whiskas.png",
//   },
//   {
//     id: 3,
//     Brand: "Whiskas",
//     ProductType: "Dog Food",
//     BreedType: "All breeds",
//     VegNonveg: "Veg",
//     src: "/assets/FilterItem/Whiskas.png",
//   },
//   {
//     id: 3,
//     Brand: "Whiskas",
//     ProductType: "Dog Food",
//     BreedType: "All breeds",
//     VegNonveg: "Veg",
//     src: "/assets/FilterItem/Whiskas.png",
//   },
//   {
//     id: 3,
//     Brand: "Whiskas",
//     ProductType: "Dog Food",
//     BreedType: "All breeds",
//     VegNonveg: "Veg",
//     src: "/assets/FilterItem/Whiskas.png",
//   },
//   {
//     id: 3,
//     Brand: "Whiskas",
//     ProductType: "Dog Food",
//     BreedType: "All breeds",
//     VegNonveg: "Veg",
//     src: "/assets/FilterItem/Whiskas.png",
//   },
];
